title: CMSC498Z Project
description: Project Website for CMSC498Z Fall 2025
theme: just-the-docs

url: https://gracelcai.github.io/cmsc498z-project-website

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://gracelcai.github.io/cmsc498z-project-website
